name: Build test

on:
  push:
    braches:
      - main
    pull_request:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      - DATABASE_URL:${{ secrets.DATABASE_URL }}
      - NEXT_APP_TELEGRAM_BOT_TOKEN :${{ secrets.NEXT_APP_TELEGRAM_BOT_TOKEN }}
    strategy:
      matrix:
        node-version: [18, 20]
    name: Node${{ matrix.node-version }}
    steps:
      - name: Checkout code
        uses: action/checkout@v3
      - name: Set up node.js
        uses: action/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm i
          npx prisma build
          npm run build
