name: Build test

 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NEXT_APP_TELEGRAM_BOT_TOKEN: ${{ secrets.NEXT_APP_TELEGRAM_BOT_TOKEN }}
  NEXT_APP_CHAT_ID: ${{ secrets.NEXT_APP_CHAT_ID }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    name: Node ${{ matrix.node-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm i
      - name: Genereate prisma
        run: npx prisma generate
      - name: Build next app
        run: npm run build
